name: PHP 7.4

on:
  schedule:
    - cron: '15 22 * * 2'
  workflow_dispatch:

env:
  # The default repo env will be 'ComputeStacks'; uppercase is not allowed.
  GH_REPO: computestacks/cs-docker-whmcs

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Github Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: php7.4/
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            cmptstks/whmcs:php7.4-litespeed
            ghcr.io/${{ env.GH_REPO }}:php7.4-litespeed
          cache-from: type=gha
          cache-to: type=gha,mode=max
